name: Docker Image CI

on:
  release:
    types: [published]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - uses: actions/cache@v3
      id: cache
      with:
        path: path/to/dependencies
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        builder: ${{ steps.buildx.outputs.name }}
        tags: "${{ secrets.DOCKER_USER }}/drupal-sniffer-junit:${{ github.ref_name }}"
        cache-from: type=gha, scope=${{ github.workflow }}
        cache-to: type=gha,mode=max, scope=${{ github.workflow }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        builder: ${{ steps.buildx.outputs.name }}
        tags: "${{ secrets.DOCKER_USER }}/drupal-sniffer-junit:latest"
        cache-from: type=gha, scope=${{ github.workflow }}
        cache-to: type=gha,mode=max, scope=${{ github.workflow }}

